theme="catppuccin_mocha"

[editor]
bufferline="multiple"
cursorline=true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert="bar"

[editor.lsp]
display-messages=true

[editor.statusline]
left=["mode", "spinner", "version-control", "file-name"]

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
