theme="adwaita-dark"
# theme="ao"
# theme="everforest_dark"
# theme="fleet_dark"
# theme="jetbrains_dark"
# theme="zed_onedark"

[editor]
true-color=true
color-modes=true
bufferline="multiple"
cursorline=true
end-of-line-diagnostics="hint"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert="bar"
normal="block"
select="underline"

[editor.lsp]
display-messages=true

[editor.statusline]
left=["mode", "spinner", "version-control", "file-name"]

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line="warning"

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
esc = ["collapse_selection", "keep_primary_selection"]
