# theme="adwaita-dark"
# theme="everforest_dark"
# theme="fleet_dark"
# theme="jetbrains_dark"
# theme="zed_onedark"
# theme="onedark"
# theme="carbon"
theme="lugh"

[editor]
true-color=true
color-modes=true
bufferline="multiple"
cursorline=true
end-of-line-diagnostics="hint"
line-number="relative"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert="bar"
normal="block"
select="underline"

[editor.lsp]
display-messages=true

[editor.statusline]
left = ["mode", "file-name", "file-modification-indicator", "spacer", "diagnostics"]
right = ["spinner", "file-type", "separator", "selections", "register", "position", "file-encoding"]
center = ["version-control"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.inline-diagnostics]
cursor-line="warning"

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
esc = ["collapse_selection", "keep_primary_selection"]
