general.import = [
  "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "alacritty"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.7
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 16

[cursor]
style.shape = "Beam"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
